kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-pod
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: mrkmod/azuritest:latest
          ports:
            - containerPort: 80
